version: 2
registries:
  github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/iikuzmychov/index.json
    username: iikuzmychov
    password: ${{secrets.GH_PACKAGES_TOKEN}}
updates:
  - package-ecosystem: "nuget"
    directory: "/frames/frame-0525"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/frames/frame-1444"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/frames/frame-2429"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/frames/frame-3413"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/frames/frame-4398"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/frames/frame-5645"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame:
        patterns: ["*"]
