version: 2
registries:
  github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/iikuzmychov/index.json
    username: iikuzmychov
    password: ${{secrets.GH_PACKAGES_TOKEN}}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0001"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-1:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0002"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-2:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0003"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-3:
        patterns: ["*"]
