version: 2
registries:
  github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/iikuzmychov/index.json
    username: iikuzmychov
    password: ${{secrets.GH_PACKAGES_TOKEN}}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0309"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-309:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0310"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-310:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0312"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-312:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0314"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-314:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0315"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-315:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0318"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-318:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0319"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-319:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0323"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-323:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0325"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-325:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0326"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-326:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0327"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-327:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0329"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-329:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0330"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-330:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0331"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-331:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0332"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-332:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0333"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-333:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0334"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-334:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0335"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-335:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0336"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-336:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0337"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-337:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0338"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-338:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0339"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-339:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0340"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-340:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0341"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-341:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0342"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-342:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0343"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-343:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0344"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-344:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0345"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-345:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0346"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-346:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "frame-0347"
    registries:
      - github-nuget
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frame-347:
        patterns: ["*"]
