<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3411L00" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L01" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L02" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L03" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L04" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L05" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L06" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L07" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L08" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L09" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L10" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L11" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L12" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L13" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L14" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L15" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L16" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L17" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L18" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L19" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L20" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L21" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L22" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.iMiMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L23" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L24" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L25" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.i.iMMMM.MMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L26" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMi.i.i.iMMMi.iMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L27" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMiMMMi.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L28" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMi.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L29" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMi.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L30" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L31" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L32" Version="1.3411.0-i.i.i.i.i.i.iMMMM.MMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L33" Version="1.3411.0-i.i.i.i.i.i.i.i.i.iMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L34" Version="1.3411.0-i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L35" Version="1.3411.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L36" Version="1.3411.0-i.i.i.i.i.i.iMi.i.i.i.i.i.M.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L37" Version="1.3411.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L38" Version="1.3411.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L39" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L40" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.MMMMMMMMM.i.i.i.iMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L41" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMi.i.i.iMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L42" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L43" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMM.MMM.MMMMMMMMM.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L44" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMM.MMM.iMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L45" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.MMM.iMMMMMMMMMM.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L46" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.MMM.MMMMMMMMMMMMM.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L47" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMM.iMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L48" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMM.iMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L49" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L50" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L51" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L52" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.MMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L53" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMi.MMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L54" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMiMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L55" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMi.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMi.M.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L56" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMi.MMMMMMMMMMMMMMM.i.i.iMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L57" Version="1.3411.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMi.iMM.MMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L58" Version="1.3411.0-i.i.i.i.i.i.iMMMi.i.MMMMMMM.i.i.i.MMMMMMMMMMMMMMMMi.iMMMMMMMM.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L59" Version="1.3411.0-i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMM.iMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L60" Version="1.3411.0-i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L61" Version="1.3411.0-i.i.i.i.i.i.i.i.i.i.i.iMiMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L62" Version="1.3411.0-i.i.i.i.i.i.iMM.i.i.i.i.MMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3411L63" Version="1.3411.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
