<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3454L00" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L01" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L02" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L03" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L04" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L05" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L06" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L07" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMiMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L08" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMiMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L09" Version="1.3454.0-i.i.i.i.i.i.iMMMMMM.i.MMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L10" Version="1.3454.0-i.i.i.i.i.i.iMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L11" Version="1.3454.0-i.i.i.i.i.i.iMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L12" Version="1.3454.0-i.i.i.i.i.i.iMMMM.i.i.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L13" Version="1.3454.0-i.i.i.i.i.i.iMMMM.i.i.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L14" Version="1.3454.0-i.i.i.i.i.i.iMMMM.i.i.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L15" Version="1.3454.0-i.i.i.i.i.i.iMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.iMi.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L16" Version="1.3454.0-i.i.i.i.i.i.iMMMMMi.i.i.MMMMMMMMMMMMM.i.i.i.iMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L17" Version="1.3454.0-i.i.i.i.i.i.iMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L18" Version="1.3454.0-i.i.i.i.i.i.iMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L19" Version="1.3454.0-i.i.i.i.i.i.iMMMMMM.i.iMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.i.M.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L20" Version="1.3454.0-i.i.i.i.i.i.iMMMMMM.i.iMMMMMMMMMMMi.M.MMi.i.iMMMMMMMMMMMiMM.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L21" Version="1.3454.0-i.i.i.i.i.i.iMMMMMi.i.iMMMMMMMMMMMM.MMMMM.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L22" Version="1.3454.0-i.i.i.i.i.i.iMMMi.i.i.iMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L23" Version="1.3454.0-i.i.i.i.i.i.i.i.i.M.i.i.MMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L24" Version="1.3454.0-i.i.i.i.i.i.i.i.MMM.i.i.MMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L25" Version="1.3454.0-i.i.i.i.i.i.i.iMMMMMi.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L26" Version="1.3454.0-i.i.i.i.i.i.i.i.iMi.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L27" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L28" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.M.i.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L29" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.M.i.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L30" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L31" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L32" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L33" Version="1.3454.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L34" Version="1.3454.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L35" Version="1.3454.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.MMMMMMMMMMMMi.M.iMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L36" Version="1.3454.0-i.i.i.i.i.i.iMMMM.iMi.i.i.i.MMMMMMMMMMMMi.M.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L37" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMi.i.i.iMMMMMMMMMMMMMi.MMiMMMMMMMMMMMMMi.MMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L38" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMi.i.iMMMMMMMMMMMMMMMi.MMiMMMMMMMMMMMMMi.MMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L39" Version="1.3454.0-i.i.i.i.i.i.iMMMMMM.i.i.MMMMMMMMMMMMMMMMi.M.iMMMMMMMMMMMMMi.MMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L40" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMi.MMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L41" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMi.MMMMiMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L42" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMiMMMMMiMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L43" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMiMMMMMiMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L44" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMiMMMMMiMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L45" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMMMi.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMiMMMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L46" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.MMMMMMMMMMiMi.i.iMMMMMMMMMM.i.i.iMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L47" Version="1.3454.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.MMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L48" Version="1.3454.0-i.i.i.i.i.i.i.MMM.iMi.i.i.i.MMMMMMMMMMiMi.i.MMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L49" Version="1.3454.0-i.i.i.i.i.i.i.i.iMMMM.i.i.iMMMMMMMM.iMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L50" Version="1.3454.0-i.i.i.i.i.i.i.i.MMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L51" Version="1.3454.0-i.i.i.i.i.i.i.i.iMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMi.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L52" Version="1.3454.0-i.i.i.i.i.i.i.i.iMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMM.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L53" Version="1.3454.0-i.i.i.i.i.i.i.i.i.M.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L54" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L55" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L56" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L57" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L58" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L59" Version="1.3454.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L60" Version="1.3454.0-i.i.i.i.i.i.iMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L61" Version="1.3454.0-i.i.i.i.i.i.iMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L62" Version="1.3454.0-i.i.i.i.i.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3454L63" Version="1.3454.0-i.i.i.i.i.i.iMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
