<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF5002L00" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L01" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L02" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L03" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L04" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L05" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L06" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L07" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L08" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L09" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L10" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L11" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L12" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L13" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L14" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L15" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L16" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L17" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L18" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L19" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L20" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMM.i.i.i.MMMMM.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L21" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.iMMMMMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L22" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMi.MMMMM.i.i.i.i.MMMMMMMMM.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L23" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMi.MMMMi.i.i.i.i.iMMMMMMMi.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L24" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMi.MMMMi.i.i.i.i.i.MMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L25" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L26" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L27" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L28" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.M.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L29" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.M.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L30" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L31" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L32" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMi.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L33" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMi.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L34" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMM.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L35" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMM.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L36" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMi.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L37" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L38" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L39" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L40" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L41" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L42" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L43" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L44" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMiMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L45" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMiMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L46" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMiMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L47" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L48" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L49" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L50" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L51" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L52" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L53" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L54" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMiMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L55" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L56" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L57" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L58" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L59" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMM.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L60" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMM.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L61" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMM.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L62" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.M.MMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5002L63" Version="1.5002.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.M.MMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
