<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4963L00" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L01" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L02" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L03" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L04" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L05" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L06" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L07" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L08" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L09" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L10" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L11" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L12" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L13" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L14" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L15" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L16" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L17" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L18" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMM.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L19" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMi.i.i.i.MMMMMMMMMMMMM.i.MMMMMMM.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L20" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMM.i.i.i.MMMMMMi.i.M.i.i.MMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L21" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMi.i.i.iMMMi.i.i.i.i.i.MMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L22" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.MMMMi.i.i.i.i.iMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L23" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L24" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L25" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L26" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L27" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L28" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L29" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L30" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L31" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.M.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L32" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.M.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L33" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMi.i.i.MMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L34" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMi.i.i.i.MMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L35" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMM.i.i.i.iMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L36" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.MMi.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L37" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L38" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L39" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L40" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMi.i.i.i.i.i.i.i.M.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L41" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L42" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L43" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L44" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L45" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L46" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L47" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L48" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L49" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L50" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L51" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L52" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L53" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L54" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L55" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.M.MMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L56" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L57" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.iMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L58" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.iMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L59" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.iMM.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L60" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.MMM.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L61" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.iMM.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L62" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.iMMMi.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4963L63" Version="1.4963.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.iMMMi.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
