<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3414L00" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L01" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L02" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L03" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L04" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L05" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L06" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L07" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L08" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L09" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L10" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L11" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L12" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L13" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L14" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L15" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L16" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L17" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L18" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMMMM.iMMMMMMMM.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L19" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMi.i.iMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L20" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L21" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMi.MMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L22" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L23" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L24" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L25" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.i.MMMMM.iMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L26" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMM.i.MMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L27" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMi.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L28" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L29" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L30" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L31" Version="1.3414.0-i.i.i.i.i.i.iMMMi.iMMMMMMMi.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L32" Version="1.3414.0-i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L33" Version="1.3414.0-i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMiMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L34" Version="1.3414.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L35" Version="1.3414.0-i.i.i.i.i.i.iMM.i.i.i.i.i.iMi.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L36" Version="1.3414.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L37" Version="1.3414.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L38" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L39" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L40" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L41" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L42" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMM.iMMMiMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L43" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.iMMMiMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L44" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.iMMMiMMMMMMMMMM.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L45" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L46" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L47" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMM.iMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L48" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMM.iMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L49" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.MMM.iMMMMMMMMMMMM.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L50" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L51" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMi.i.i.i.iMMMMMMMMMi.MMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L52" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.i.MMMMMMMMMMi.MMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L53" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.iMMMMMMMMMiMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L54" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMi.MMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L55" Version="1.3414.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMi.MMMMMMMMMMMMMMMMM.i.MMiMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L56" Version="1.3414.0-i.i.i.i.i.i.iMMMM.iMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L57" Version="1.3414.0-i.i.i.i.i.i.iMM.i.i.MMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L58" Version="1.3414.0-i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L59" Version="1.3414.0-i.i.i.i.i.i.i.i.i.i.i.iMM.M.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.MMM.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L60" Version="1.3414.0-i.i.i.i.i.i.iMM.i.i.i.i.iMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L61" Version="1.3414.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L62" Version="1.3414.0-i.i.i.i.i.i.iMMMM.i.i.i.i.MMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3414L63" Version="1.3414.0-i.i.i.i.i.i.iMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
