<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3373L00" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L01" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L02" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L03" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L04" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L05" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L06" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L07" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L08" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L09" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L10" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L11" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L12" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L13" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L14" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L15" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L16" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L17" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L18" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L19" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L20" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L21" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L22" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L23" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L24" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L25" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L26" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L27" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L28" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L29" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L30" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L31" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L32" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L33" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L34" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L35" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L36" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L37" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L38" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L39" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L40" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L41" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L42" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L43" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L44" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L45" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L46" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMM.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L47" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L48" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.iMMMiMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L49" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L50" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L51" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L52" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L53" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L54" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L55" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L56" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L57" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L58" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L59" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L60" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L61" Version="1.3373.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L62" Version="1.3373.0-i.i.i.i.i.i.i.iMMMMMM.i.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3373L63" Version="1.3373.0-i.i.i.i.i.i.i.iMMMM.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
