<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3422L00" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L01" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L02" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L03" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L04" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L05" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L06" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L07" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L08" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L09" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L10" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L11" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L12" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L13" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L14" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L15" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L16" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L17" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L18" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMi.MMMMMMMMMMMMi.i.iMM.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L19" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L20" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L21" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.i.iMiMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L22" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L23" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L24" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L25" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.iMMMMMMMMMMMi.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L26" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.iMMMMMMMMMMMi.i.i.i.iMMMi.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L27" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMi.iMMMMMMMMMMMi.iMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L28" Version="1.3422.0-i.i.i.i.i.i.iMMMM.iMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L29" Version="1.3422.0-i.i.i.i.i.i.i.i.i.i.M.i.i.MMi.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L30" Version="1.3422.0-i.i.i.i.i.i.i.i.i.i.i.M.MMMMi.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L31" Version="1.3422.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L32" Version="1.3422.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L33" Version="1.3422.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L34" Version="1.3422.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L35" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L36" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L37" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L38" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L39" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.MMiMMMMMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L40" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.MMiMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L41" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.MMiMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L42" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.MMiMMMMMMMMMMMMMM.MMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L43" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMiMMMiMMMMMMMMMMMMMi.MMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L44" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMiMMMiMMMMMMMMMMMMMi.MMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L45" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMiMMMiMMMMMMMMMMMM.iMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L46" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.i.iMMMMMMMMMM.iMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L47" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.i.iMMMMMMMMMM.MMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L48" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMM.i.i.iMMMMMMMMMi.MMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L49" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMi.MMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L50" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMi.MMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L51" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.M.iMMMMMMMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L52" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L53" Version="1.3422.0-i.i.i.i.i.i.iMMMM.i.iMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L54" Version="1.3422.0-i.i.i.i.i.i.iMM.i.i.i.MMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMiMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L55" Version="1.3422.0-i.i.i.i.i.i.iMM.i.i.i.i.iMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L56" Version="1.3422.0-i.i.i.i.i.i.iMMMi.i.i.i.MMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L57" Version="1.3422.0-i.i.i.i.i.i.iMMMM.i.i.i.iMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L58" Version="1.3422.0-i.i.i.i.i.i.iMMMM.i.i.i.i.M.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMM.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L59" Version="1.3422.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMi.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L60" Version="1.3422.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMi.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L61" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMM.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L62" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3422L63" Version="1.3422.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.M.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
