<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF2804L00" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L01" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L02" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L03" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L04" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L05" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L06" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L07" Version="1.2804.0-i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L08" Version="1.2804.0-i.i.i.i.i.i.i.M.iMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L09" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L10" Version="1.2804.0-i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L11" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L12" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L13" Version="1.2804.0-i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L14" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L15" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L16" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L17" Version="1.2804.0-i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L18" Version="1.2804.0-i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L19" Version="1.2804.0-i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L20" Version="1.2804.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L21" Version="1.2804.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L22" Version="1.2804.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L23" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L24" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L25" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L26" Version="1.2804.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L27" Version="1.2804.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L28" Version="1.2804.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L29" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L30" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMMMM.MMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L31" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L32" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L33" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L34" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMMMiMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L35" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMM.iMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L36" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMM.iMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L37" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMM.iMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L38" Version="1.2804.0-i.i.i.i.i.i.i.iMMMMMM.iMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L39" Version="1.2804.0-0" />
    <PackageReference Include="BAF2804L40" Version="1.2804.0-i.i.i.i.i.i.i.i.iMM.i.MMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L41" Version="1.2804.0-i.i.i.i.i.i.i.i.iMM.i.MMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L42" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L43" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L44" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L45" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L46" Version="1.2804.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L47" Version="1.2804.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L48" Version="1.2804.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L49" Version="1.2804.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L50" Version="1.2804.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L51" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L52" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L53" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L54" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L55" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L56" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L57" Version="1.2804.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L58" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L59" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L60" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L61" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.iMMMiMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L62" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.iMM.iMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2804L63" Version="1.2804.0-i.i.i.i.i.i.i.i.i.i.i.iMM.iMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
