<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4951L00" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L01" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L02" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L03" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L04" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L05" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L06" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L07" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L08" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L09" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L10" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L11" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L12" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L13" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L14" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L15" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L16" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L17" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L18" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L19" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMiMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L20" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMi.i.iMi.iMi.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L21" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.iMi.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L22" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L23" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L24" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L25" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L26" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMi.i.i.i.i.i.iMi.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L27" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L28" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L29" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMi.i.MMiMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L30" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L31" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.M.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L32" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L33" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L34" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L35" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L36" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L37" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L38" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.i.i.M.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L39" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L40" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L41" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L42" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L43" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L44" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L45" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L46" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L47" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L48" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L49" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L50" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L51" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L52" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L53" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L54" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.i.M.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L55" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.iMMMi.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L56" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.i.iMMMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L57" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.i.iMMMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L58" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.MMMMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L59" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.MMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L60" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L61" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L62" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4951L63" Version="1.4951.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.iMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
