<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF5005L00" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L01" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.MMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L02" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L03" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L04" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L05" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L06" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L07" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L08" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L09" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L10" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L11" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.M.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L12" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L13" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L14" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L15" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.MMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L16" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.MMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L17" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L18" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L19" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L20" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.iMMMMMMMi.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L21" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMi.iMMMMMM.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L22" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMi.iMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L23" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMi.iMMMMMi.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L24" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMi.MMMMM.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L25" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMM.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L26" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.M.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L27" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.M.i.i.iMMMMMMMMMMMiMMMi.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L28" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.M.i.i.iMMMMMMMMMMMi.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L29" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.M.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L30" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L31" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L32" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMi.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L33" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMM.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L34" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMM.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L35" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMi.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L36" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.M.MMi.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L37" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMM.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L38" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMi.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L39" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMi.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L40" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L41" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L42" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L43" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L44" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L45" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L46" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMM.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L47" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMM.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L48" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L49" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L50" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L51" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L52" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L53" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L54" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L55" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L56" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L57" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMiMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L58" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMiMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L59" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMiMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L60" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L61" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L62" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5005L63" Version="1.5005.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
