<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3458L00" Version="1.3458.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L01" Version="1.3458.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L02" Version="1.3458.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L03" Version="1.3458.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L04" Version="1.3458.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L05" Version="1.3458.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L06" Version="1.3458.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L07" Version="1.3458.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L08" Version="1.3458.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L09" Version="1.3458.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L10" Version="1.3458.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L11" Version="1.3458.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L12" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L13" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L14" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L15" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMi.MMMMMMi.i.iMi.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L16" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.iMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L17" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L18" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L19" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L20" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L21" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.iMi.i.iMMMMMMMMMMMiMMMi.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L22" Version="1.3458.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L23" Version="1.3458.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L24" Version="1.3458.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L25" Version="1.3458.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L26" Version="1.3458.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L27" Version="1.3458.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L28" Version="1.3458.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L29" Version="1.3458.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L30" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L31" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L32" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L33" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L34" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L35" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L36" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L37" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.M.iMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L38" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.M.iMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L39" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L40" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMM.iMM.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L41" Version="1.3458.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMM.iMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L42" Version="1.3458.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMM.iMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L43" Version="1.3458.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.MMi.MMMMMMMMMMMMM.iMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L44" Version="1.3458.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.iMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L45" Version="1.3458.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.iMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L46" Version="1.3458.0-i.i.i.i.i.i.iMM.i.iMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.MMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L47" Version="1.3458.0-i.i.i.i.i.i.iMMMi.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMM.iMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L48" Version="1.3458.0-i.i.i.i.i.i.iMMMi.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.MMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L49" Version="1.3458.0-i.i.i.i.i.i.iMM.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMM.MMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L50" Version="1.3458.0-i.i.i.i.i.i.iMi.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMM.iMMMi.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L51" Version="1.3458.0-i.i.i.i.i.i.iMi.i.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L52" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L53" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.MMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L54" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L55" Version="1.3458.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.MMMMMMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L56" Version="1.3458.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMM.iMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L57" Version="1.3458.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L58" Version="1.3458.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L59" Version="1.3458.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L60" Version="1.3458.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L61" Version="1.3458.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L62" Version="1.3458.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3458L63" Version="1.3458.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
