<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4948L00" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L01" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L02" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L03" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L04" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L05" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L06" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L07" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L08" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L09" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L10" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L11" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L12" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L13" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L14" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L15" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L16" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L17" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L18" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L19" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.MMM.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L20" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMM.i.i.iMi.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L21" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L22" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L23" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L24" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.M.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L25" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.M.i.i.i.i.i.i.MMM.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L26" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMi.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L27" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L28" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L29" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L30" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L31" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMM.i.MMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L32" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L33" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L34" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L35" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L36" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L37" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L38" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.i.iMiMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L39" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L40" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L41" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L42" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L43" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L44" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L45" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L46" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.M.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L47" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L48" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L49" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L50" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L51" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L52" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L53" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.i.M.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L54" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.i.M.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L55" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.iMMMi.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L56" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.iMMMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L57" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L58" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L59" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L60" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L61" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L62" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4948L63" Version="1.4948.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.MMi.i.i.i.i.MMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
