<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3434L00" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L01" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L02" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L03" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L04" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L05" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L06" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L07" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L08" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L09" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L10" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMi.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L11" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L12" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L13" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L14" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMM.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L15" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L16" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L17" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L18" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L19" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L20" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.M.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L21" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMM.i.i.MMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L22" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.iMM.iMMMMMMMMMMMMMMMi.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L23" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMi.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L24" Version="1.3434.0-i.i.i.i.i.i.iMMMMMiMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMi.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L25" Version="1.3434.0-i.i.i.i.i.i.iMM.i.i.MMM.i.M.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L26" Version="1.3434.0-i.i.i.i.i.i.iMi.i.i.i.i.iMM.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L27" Version="1.3434.0-i.i.i.i.i.i.iMi.i.i.i.i.MMi.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L28" Version="1.3434.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L29" Version="1.3434.0-i.i.i.i.i.i.iMMMM.i.i.i.i.iMi.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L30" Version="1.3434.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L31" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L32" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L33" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L34" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMM.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L35" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMM.iMM.iMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L36" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMM.iMMMiMMMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L37" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.iMMMiMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L38" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.iMMMiMMMMMMMMMMMMMMMi.M.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L39" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.iMMMiMMMMMMMMMMMMMMMi.M.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L40" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.iMMMiMMMMMMMMMMMMMM.iMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L41" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.iMMMiMMMMMMMMMMMMMM.iMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L42" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.MMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L43" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.MMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L44" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMiMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L45" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMiMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L46" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMiMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L47" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L48" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.iMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L49" Version="1.3434.0-i.i.i.i.i.i.iMMMMMi.i.MMMMi.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L50" Version="1.3434.0-i.i.i.i.i.i.iMMMi.i.i.iMM.M.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L51" Version="1.3434.0-i.i.i.i.i.i.iMMMi.i.i.i.iMMMi.i.i.MMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L52" Version="1.3434.0-i.i.i.i.i.i.iMMMM.i.i.i.iMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L53" Version="1.3434.0-i.i.i.i.i.i.iMMMM.i.i.i.i.M.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L54" Version="1.3434.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L55" Version="1.3434.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L56" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L57" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L58" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L59" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L60" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L61" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L62" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3434L63" Version="1.3434.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
