<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3403L00" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L01" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L02" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L03" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L04" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L05" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L06" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L07" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L08" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L09" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L10" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L11" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L12" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L13" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L14" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L15" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L16" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L17" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L18" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L19" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L20" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L21" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L22" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L23" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L24" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L25" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L26" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.MMiMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L27" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L28" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMM.MMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L29" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L30" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L31" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L32" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L33" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMM.i.i.i.i.MMMMMMMMMMM.iMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L34" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMM.i.iMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L35" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMiMMMi.i.MMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L36" Version="1.3403.0-i.i.i.i.i.i.iMMMi.MMM.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L37" Version="1.3403.0-i.i.i.i.i.i.i.i.i.i.i.iMM.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L38" Version="1.3403.0-i.i.i.i.i.i.i.i.i.i.i.MMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L39" Version="1.3403.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L40" Version="1.3403.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L41" Version="1.3403.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L42" Version="1.3403.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L43" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L44" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L45" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L46" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMi.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L47" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L48" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L49" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L50" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMiMM.MMMMMMMMMMMMMMi.MMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L51" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMiMM.MMMMMMMMMMMMMMi.MMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L52" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMiMM.iMMMMMMMMMMMMMi.MMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L53" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMiMM.iMMMMMMMMMMMMMi.MMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L54" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMiMM.iMMMMMMMMMMMMMi.MMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L55" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMiMMMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L56" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMiMMMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L57" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMiMMMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L58" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMiMMMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L59" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMiMMMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L60" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.iMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L61" Version="1.3403.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L62" Version="1.3403.0-i.i.i.i.i.i.iMMMi.MMM.MMi.i.i.i.MMMMMMMMMMi.M.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3403L63" Version="1.3403.0-i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.iMMMMMMMMMiMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
