<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF6274L00" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L01" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L02" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L03" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L04" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L05" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L06" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L07" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L08" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L09" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L10" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L11" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L12" Version="1.6274.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L13" Version="1.6274.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L14" Version="1.6274.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L15" Version="1.6274.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L16" Version="1.6274.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L17" Version="1.6274.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L18" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L19" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L20" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L21" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L22" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L23" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L24" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L25" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L26" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L27" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L28" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L29" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L30" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L31" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L32" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L33" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L34" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L35" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L36" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L37" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L38" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L39" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L40" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L41" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L42" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L43" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L44" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L45" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L46" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L47" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L48" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L49" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L50" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L51" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.MMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L52" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L53" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L54" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L55" Version="1.6274.0-0" />
    <PackageReference Include="BAF6274L56" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L57" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L58" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L59" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L60" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L61" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L62" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6274L63" Version="1.6274.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
