<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4741L00" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L01" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L02" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L03" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L04" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L05" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L06" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L07" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L08" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L09" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L10" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L11" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L12" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L13" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L14" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L15" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L16" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L17" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L18" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L19" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L20" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L21" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L22" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L23" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L24" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L25" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMi.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L26" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L27" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L28" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L29" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L30" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L31" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L32" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L33" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMi.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L34" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMMMi.i.i.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L35" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.MMMMi.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L36" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.MMMMi.i.iMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L37" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMM.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L38" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.iMMMM.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L39" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMi.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L40" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMi.i.MMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L41" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMM.i.MMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L42" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMM.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L43" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.iMM.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L44" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.M.i.iMM.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L45" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L46" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.iMi.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L47" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L48" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMiMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L49" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L50" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L51" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L52" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L53" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.M.MMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L54" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.M.MMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L55" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.M.MMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L56" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L57" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L58" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L59" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L60" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L61" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L62" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4741L63" Version="1.4741.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
