<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4999L00" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L01" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L02" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L03" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L04" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L05" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L06" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.MMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L07" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L08" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L09" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L10" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L11" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L12" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L13" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L14" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L15" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L16" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L17" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L18" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L19" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L20" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMM.i.i.i.MMMMi.MMMMMMMMMMMMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L21" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.iMMMM.i.i.i.MMMMMMMMM.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L22" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMi.MMMMi.i.i.i.iMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L23" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMi.MMMMi.i.i.i.i.M.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L24" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMi.MMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L25" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L26" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L27" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L28" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMi.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L29" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L30" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L31" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L32" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.M.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L33" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.M.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L34" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMi.i.i.MMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L35" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMM.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L36" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L37" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMi.i.i.M.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L38" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L39" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L40" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L41" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L42" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L43" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.M.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L44" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.M.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L45" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L46" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L47" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L48" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L49" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L50" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L51" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L52" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L53" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L54" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L55" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L56" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L57" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L58" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L59" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L60" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L61" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L62" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4999L63" Version="1.4999.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
