<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4768L00" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L01" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L02" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L03" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L04" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L05" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L06" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L07" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L08" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L09" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L10" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L11" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L12" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L13" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L14" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L15" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L16" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L17" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L18" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L19" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L20" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L21" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L22" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.iMM.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L23" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L24" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.iMM.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L25" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.iMi.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L26" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.iMi.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L27" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L28" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMi.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L29" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMiMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L30" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L31" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L32" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L33" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L34" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L35" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L36" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L37" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L38" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L39" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L40" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L41" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L42" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L43" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L44" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L45" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L46" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L47" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L48" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L49" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L50" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L51" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMM.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L52" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L53" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L54" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L55" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L56" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L57" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L58" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L59" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L60" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L61" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L62" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4768L63" Version="1.4768.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
