<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF6102L00" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMiMMMM.iMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L01" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMiMMMM.MMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L02" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L03" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L04" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L05" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L06" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L07" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L08" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L09" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L10" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L11" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L12" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L13" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L14" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L15" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L16" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L17" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.iMMMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L18" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.iMMMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L19" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.iMMMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L20" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.iMMMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L21" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.MMMMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L22" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L23" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L24" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L25" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L26" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L27" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L28" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L29" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.iMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L30" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L31" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L32" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.MMMMMMM.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L33" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L34" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L35" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L36" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L37" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L38" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L39" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L40" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L41" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L42" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L43" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L44" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L45" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L46" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L47" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L48" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L49" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMi.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L50" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMM.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L51" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L52" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMi.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L53" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L54" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L55" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L56" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L57" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMMMM.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L58" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMMMi.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L59" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMMMi.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L60" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L61" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.iMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L62" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.iMMMMMMMi.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6102L63" Version="1.6102.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.iMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
