<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF5722L00" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L01" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L02" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L03" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L04" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L05" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L06" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L07" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L08" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L09" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L10" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L11" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L12" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L13" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L14" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L15" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L16" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L17" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L18" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L19" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L20" Version="1.5722.0-i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L21" Version="1.5722.0-i.i.i.i.i.i.i.MMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L22" Version="1.5722.0-i.i.i.i.i.i.i.MMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L23" Version="1.5722.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L24" Version="1.5722.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L25" Version="1.5722.0-i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L26" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L27" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L28" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L29" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L30" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L31" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L32" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L33" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L34" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L35" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L36" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L37" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L38" Version="1.5722.0-i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.MMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L39" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.iMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L40" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L41" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMiMM.i.i.MMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L42" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L43" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L44" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L45" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L46" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L47" Version="1.5722.0-i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L48" Version="1.5722.0-i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L49" Version="1.5722.0-i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L50" Version="1.5722.0-i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L51" Version="1.5722.0-i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L52" Version="1.5722.0-i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L53" Version="1.5722.0-i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L54" Version="1.5722.0-i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L55" Version="1.5722.0-i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L56" Version="1.5722.0-i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L57" Version="1.5722.0-i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L58" Version="1.5722.0-i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L59" Version="1.5722.0-i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L60" Version="1.5722.0-i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L61" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L62" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5722L63" Version="1.5722.0-i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
