<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF6073L00" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L01" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L02" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L03" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L04" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L05" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L06" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L07" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L08" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L09" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L10" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L11" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L12" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L13" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L14" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L15" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMi.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L16" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L17" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L18" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L19" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L20" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L21" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L22" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L23" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L24" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L25" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L26" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L27" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L28" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L29" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L30" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L31" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L32" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L33" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L34" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L35" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L36" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L37" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L38" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L39" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L40" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L41" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L42" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L43" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L44" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L45" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L46" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L47" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L48" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L49" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L50" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L51" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L52" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L53" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L54" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L55" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMiMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L56" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMiMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L57" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L58" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L59" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMiMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L60" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L61" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L62" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6073L63" Version="1.6073.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
