<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3440L00" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L01" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L02" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L03" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L04" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L05" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L06" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L07" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L08" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L09" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMi.iMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L10" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMi.i.M.i.iMMMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L11" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMi.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L12" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L13" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L14" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMM.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L15" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L16" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L17" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L18" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L19" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L20" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L21" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L22" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L23" Version="1.3440.0-i.i.i.i.i.i.iMMMM.iMMMMMi.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMi.i.iMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L24" Version="1.3440.0-i.i.i.i.i.i.i.i.i.i.MMM.iMi.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMi.i.iMMMi.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L25" Version="1.3440.0-i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.MMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L26" Version="1.3440.0-i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L27" Version="1.3440.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L28" Version="1.3440.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L29" Version="1.3440.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L30" Version="1.3440.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L31" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L32" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.iMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L33" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMiMMMi.MMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L34" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L35" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMi.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L36" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMi.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L37" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L38" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L39" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMi.MMM.MMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L40" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L41" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.iMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L42" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMi.MMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L43" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMiMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L44" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMiMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L45" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L46" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMiMMMi.MMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L47" Version="1.3440.0-i.i.i.i.i.i.iMMMMMM.MMMMMMM.i.i.iMMMMMMMMMiMM.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L48" Version="1.3440.0-i.i.i.i.i.i.iMMMM.i.iMMMMMi.i.i.MMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L49" Version="1.3440.0-i.i.i.i.i.i.iMM.i.i.i.MMiMM.i.iMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L50" Version="1.3440.0-i.i.i.i.i.i.iMM.i.i.i.i.MMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L51" Version="1.3440.0-i.i.i.i.i.i.iMMMi.i.i.i.MMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L52" Version="1.3440.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L53" Version="1.3440.0-i.i.i.i.i.i.iMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L54" Version="1.3440.0-i.i.i.i.i.i.iMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L55" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMi.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L56" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L57" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L58" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L59" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L60" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L61" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L62" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3440L63" Version="1.3440.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
