<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3941L00" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L01" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L02" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L03" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L04" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L05" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L06" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L07" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L08" Version="1.3941.0-i.i.i.i.i.i.iMMMMMM.i.iMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L09" Version="1.3941.0-i.i.i.i.i.i.iMMMMMM.i.MMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L10" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L11" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L12" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L13" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L14" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L15" Version="1.3941.0-i.i.i.i.i.i.iMMMMMM.i.iMi.i.i.iMMMMMMMMMMMMMiMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L16" Version="1.3941.0-i.i.i.i.i.i.iMMMMMi.iMMMi.i.i.iMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L17" Version="1.3941.0-i.i.i.i.i.i.iMMMMMi.MMM.i.i.i.iMMMMMMMMMMMM.i.MMM.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L18" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L19" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L20" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L21" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L22" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L23" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L24" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L25" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L26" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L27" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L28" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L29" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L30" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L31" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L32" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L33" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L34" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.iMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L35" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.MMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L36" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.iMMMMMMMi.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L37" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.MMMMMMi.iMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L38" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.iMMMMMi.iMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L39" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.MMMMi.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L40" Version="1.3941.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.MMMMi.iMiMMMi.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L41" Version="1.3941.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L42" Version="1.3941.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L43" Version="1.3941.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L44" Version="1.3941.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L45" Version="1.3941.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L46" Version="1.3941.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L47" Version="1.3941.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L48" Version="1.3941.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L49" Version="1.3941.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L50" Version="1.3941.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L51" Version="1.3941.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L52" Version="1.3941.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L53" Version="1.3941.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L54" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L55" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L56" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L57" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L58" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L59" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L60" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L61" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.M.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L62" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.iMM.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3941L63" Version="1.3941.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.iMM.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
