<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF2895L00" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L01" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L02" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMiMM.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L03" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMiMM.MMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L04" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L05" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.iMi.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L06" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.MMi.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L07" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.MMi.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L08" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.i.MMi.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L09" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMi.i.i.i.iMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L10" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.MMi.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L11" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.iMi.i.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L12" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.iMi.iMMMi.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L13" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.iMMMMMMMM.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L14" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.iMMMMMMMMMiMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L15" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L16" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L17" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L18" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L19" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L20" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L21" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L22" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L23" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L24" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L25" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L26" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L27" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L28" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L29" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L30" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L31" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMi.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L32" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMM.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L33" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMM.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L34" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMM.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L35" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L36" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L37" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L38" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L39" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L40" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L41" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L42" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L43" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L44" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L45" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L46" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L47" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L48" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.iMi.iMiMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L49" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.iMi.M.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L50" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.iMi.M.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L51" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.M.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L52" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L53" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L54" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L55" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L56" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L57" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L58" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L59" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L60" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L61" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L62" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2895L63" Version="1.2895.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
