<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4932L00" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L01" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L02" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L03" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L04" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L05" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L06" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L07" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L08" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L09" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L10" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L11" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L12" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L13" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L14" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L15" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L16" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L17" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L18" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMiMM.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L19" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMM.i.i.M.i.i.i.iMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L20" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L21" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L22" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L23" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L24" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L25" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L26" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L27" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L28" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L29" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L30" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L31" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMM.i.MMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L32" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L33" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L34" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L35" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L36" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.i.iMiMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L37" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L38" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L39" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L40" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L41" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L42" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L43" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L44" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L45" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L46" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.M.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L47" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L48" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L49" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L50" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L51" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L52" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L53" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.M.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L54" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMM.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L55" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.i.i.iMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L56" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.MMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L57" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L58" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L59" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.MMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L60" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L61" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMM.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L62" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.MMM.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4932L63" Version="1.4932.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMM.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
