<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3632L00" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L01" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L02" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L03" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L04" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L05" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L06" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L07" Version="1.3632.0-0" />
    <PackageReference Include="BAF3632L08" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L09" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L10" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L11" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L12" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L13" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L14" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L15" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L16" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L17" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L18" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L19" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L20" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L21" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L22" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L23" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L24" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L25" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L26" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L27" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L28" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L29" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L30" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L31" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L32" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L33" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L34" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L35" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L36" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L37" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L38" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L39" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L40" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L41" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L42" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L43" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L44" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L45" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L46" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L47" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L48" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L49" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L50" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L51" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L52" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L53" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L54" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L55" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L56" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L57" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L58" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L59" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L60" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L61" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L62" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3632L63" Version="1.3632.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
