<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4907L00" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L01" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L02" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L03" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L04" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L05" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L06" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L07" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L08" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L09" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L10" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L11" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L12" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L13" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L14" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L15" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L16" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMM.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L17" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMi.i.M.iMi.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L18" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L19" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L20" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L21" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.M.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L22" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L23" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L24" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L25" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L26" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L27" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L28" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L29" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L30" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.M.i.i.MMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L31" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L32" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L33" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMi.i.MMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L34" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L35" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L36" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L37" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L38" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L39" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L40" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L41" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L42" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L43" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L44" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L45" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMi.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L46" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L47" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L48" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L49" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L50" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L51" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.M.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L52" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.i.M.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L53" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMM.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L54" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L55" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L56" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L57" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L58" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L59" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.iMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L60" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L61" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMM.i.i.i.i.iMMMi.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L62" Version="1.4907.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.MMi.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4907L63" Version="1.4907.0-0" />
  </ItemGroup>
</Project>
