<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3784L00" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L01" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L02" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L03" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L04" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L05" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L06" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L07" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L08" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L09" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L10" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L11" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L12" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L13" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L14" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L15" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L16" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L17" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L18" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L19" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L20" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L21" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.iMi.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L22" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMi.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L23" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.MMi.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L24" Version="1.3784.0-i.i.i.i.i.i.i.i.iMi.i.i.i.iMMMi.i.i.iMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L25" Version="1.3784.0-i.i.i.i.i.i.iMiMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L26" Version="1.3784.0-i.i.i.i.i.i.iMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L27" Version="1.3784.0-i.i.i.i.i.i.iMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L28" Version="1.3784.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L29" Version="1.3784.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L30" Version="1.3784.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L31" Version="1.3784.0-i.i.i.i.i.i.iMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L32" Version="1.3784.0-i.i.i.i.i.i.iMMMi.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L33" Version="1.3784.0-i.i.i.i.i.i.iMM.i.i.MMMMMMMMMMMMMMM.i.i.iMMMMMMMiMMMMMMMMMMMi.i.i.i.MMMMi.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L34" Version="1.3784.0-i.i.i.i.i.i.iMM.i.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMiMMMM.i.iMM.i.i.i.i.iMi.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L35" Version="1.3784.0-i.i.i.i.i.i.iMi.i.i.i.MMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L36" Version="1.3784.0-i.i.i.i.i.i.iMi.i.i.i.iMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L37" Version="1.3784.0-i.i.i.i.i.i.iMi.i.i.i.i.MMMMi.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L38" Version="1.3784.0-i.i.i.i.i.i.iMi.i.i.i.i.MMi.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L39" Version="1.3784.0-i.i.i.i.i.i.iMi.i.i.i.i.iMi.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L40" Version="1.3784.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L41" Version="1.3784.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMM.iMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L42" Version="1.3784.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L43" Version="1.3784.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L44" Version="1.3784.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L45" Version="1.3784.0-i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L46" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L47" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMiMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L48" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.iMMMMMMMMMi.MMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L49" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.iMMMMMMMMMM.MMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L50" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMM.MMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L51" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMM.MMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L52" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L53" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L54" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L55" Version="1.3784.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L56" Version="1.3784.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L57" Version="1.3784.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L58" Version="1.3784.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L59" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L60" Version="1.3784.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L61" Version="1.3784.0-i.i.i.i.i.i.i.i.iMM.i.i.i.iMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L62" Version="1.3784.0-i.i.i.i.i.i.i.i.MMM.i.i.i.iMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3784L63" Version="1.3784.0-i.i.i.i.i.i.i.MMMMMMi.i.i.iMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
