<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF2865L00" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L01" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L02" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L03" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L04" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L05" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L06" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L07" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMi.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L08" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.MMMMi.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L09" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.MMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L10" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L11" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L12" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L13" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L14" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L15" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L16" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L17" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L18" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L19" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L20" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L21" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L22" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L23" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L24" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L25" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L26" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L27" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L28" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L29" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.iMM.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L30" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMiMM.i.i.i.i.i.iMM.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L31" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.iMM.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L32" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L33" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMM.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L34" Version="1.2865.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L35" Version="1.2865.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.MMM.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L36" Version="1.2865.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.MMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L37" Version="1.2865.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.iMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L38" Version="1.2865.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L39" Version="1.2865.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L40" Version="1.2865.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L41" Version="1.2865.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L42" Version="1.2865.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L43" Version="1.2865.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMM.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L44" Version="1.2865.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMM.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L45" Version="1.2865.0-i.i.i.i.i.i.i.MMMMM.MMMMMMMMMMMMMMMMMMM.i.MMMMMMi.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L46" Version="1.2865.0-i.i.i.i.i.i.i.i.M.i.MMMMMMM.MMMMMMMMMMi.MMMMM.MMMMi.MMMMMMMMMMiMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L47" Version="1.2865.0-i.i.i.i.i.i.i.i.i.iMMMMMMMi.MMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.MMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L48" Version="1.2865.0-i.i.i.i.i.i.i.i.i.iMMMMMM.i.MMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.iMiMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L49" Version="1.2865.0-i.i.i.i.i.i.i.i.i.MMMMM.M.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.M.MMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L50" Version="1.2865.0-i.i.i.i.i.i.i.i.i.MMMMMMi.i.MMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L51" Version="1.2865.0-i.i.i.i.i.i.i.i.i.MMMMi.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMM.i.i.iMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L52" Version="1.2865.0-i.i.i.i.i.i.i.i.i.MMM.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L53" Version="1.2865.0-i.i.i.i.i.i.i.i.i.M.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.M.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L54" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L55" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L56" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L57" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L58" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L59" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L60" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L61" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L62" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2865L63" Version="1.2865.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
