<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF2726L00" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.iMMMM.iMMMMMMMMMMMMMMMMMMMi.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L01" Version="1.2726.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMM.iMMMMMMMMMMMMMMMMMMMi.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L02" Version="1.2726.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMM.MMMMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L03" Version="1.2726.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMM.MMMMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L04" Version="1.2726.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L05" Version="1.2726.0-i.i.i.i.i.i.i.iMi.MMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMM.MMi.MMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L06" Version="1.2726.0-i.i.i.i.i.i.i.MMM.MMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L07" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L08" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L09" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMi.MMMMMMMMMMMMMMMMMMM.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L10" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L11" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMi.iMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L12" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMi.iMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L13" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L14" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L15" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L16" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L17" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L18" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L19" Version="1.2726.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L20" Version="1.2726.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L21" Version="1.2726.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMi.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L22" Version="1.2726.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMi.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L23" Version="1.2726.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMi.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L24" Version="1.2726.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.M.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L25" Version="1.2726.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L26" Version="1.2726.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L27" Version="1.2726.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L28" Version="1.2726.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L29" Version="1.2726.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L30" Version="1.2726.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L31" Version="1.2726.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L32" Version="1.2726.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L33" Version="1.2726.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L34" Version="1.2726.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L35" Version="1.2726.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L36" Version="1.2726.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L37" Version="1.2726.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L38" Version="1.2726.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L39" Version="1.2726.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L40" Version="1.2726.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L41" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L42" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L43" Version="1.2726.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L44" Version="1.2726.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L45" Version="1.2726.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L46" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L47" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L48" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L49" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L50" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L51" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMiMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L52" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMiMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L53" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.MMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L54" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.MMMMMMMMMMMMMMMMMMiMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L55" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.MMMMMMMMMMMMMMMMMMiMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L56" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L57" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L58" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L59" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L60" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L61" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L62" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2726L63" Version="1.2726.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
