<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3981L00" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L01" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L02" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L03" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L04" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L05" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L06" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L07" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L08" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L09" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L10" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L11" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L12" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L13" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L14" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L15" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L16" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L17" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L18" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMi.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L19" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMM.i.i.i.i.M.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L20" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMM.iMMMi.i.i.i.iMi.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L21" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.iMM.i.i.i.i.i.M.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L22" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.iMM.i.i.i.i.i.M.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L23" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.iMM.i.i.i.i.i.MMi.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L24" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMM.iMM.i.i.i.i.i.MMi.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L25" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.iMM.i.i.i.i.i.MMi.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L26" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.iMi.i.i.i.i.i.MMM.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L27" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.i.M.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L28" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMi.i.iMM.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L29" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L30" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L31" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L32" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMM.i.i.iMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L33" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.MMM.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L34" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.MMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L35" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMi.iMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L36" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMi.iMM.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L37" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.iMi.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L38" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.MMi.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L39" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.iMM.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L40" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMi.i.MMM.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L41" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMM.i.i.MMM.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L42" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMi.i.iMMMi.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L43" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMi.iMMMMMi.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L44" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMi.iMMMMMi.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L45" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMM.iMMMM.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L46" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMM.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L47" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L48" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L49" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L50" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L51" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L52" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L53" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L54" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L55" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L56" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L57" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L58" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L59" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L60" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L61" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L62" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3981L63" Version="1.3981.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
