<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4760L00" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L01" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L02" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L03" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L04" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L05" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L06" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L07" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L08" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L09" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L10" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L11" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L12" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L13" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L14" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L15" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L16" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L17" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L18" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L19" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L20" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L21" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L22" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L23" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L24" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L25" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.M.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L26" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L27" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L28" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMiMi.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L29" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L30" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L31" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L32" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L33" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMiMM.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L34" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L35" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L36" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L37" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L38" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L39" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L40" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMMMMMMMMMMMi.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L41" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMi.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L42" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMi.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L43" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L44" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L45" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L46" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L47" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMi.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L48" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMi.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L49" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMi.i.i.i.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L50" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.iMM.i.iMM.i.i.i.i.i.i.MMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L51" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.M.i.MMM.i.i.i.i.i.M.MMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L52" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMMMM.i.i.i.i.i.M.MMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L53" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMM.i.i.i.i.i.M.MMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L54" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.M.MMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L55" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.M.MMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L56" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L57" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L58" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L59" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L60" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L61" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L62" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4760L63" Version="1.4760.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
