<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3435L00" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L01" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L02" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L03" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L04" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L05" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L06" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L07" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L08" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L09" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L10" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMi.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L11" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L12" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L13" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L14" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.i.MMM.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L15" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L16" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L17" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L18" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L19" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L20" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L21" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.iMiMMMMMMMMMMMMMMMM.i.i.MMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L22" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L23" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L24" Version="1.3435.0-i.i.i.i.i.i.iMMMMMi.MMMMi.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L25" Version="1.3435.0-i.i.i.i.i.i.iMi.i.i.MMi.i.M.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L26" Version="1.3435.0-i.i.i.i.i.i.iMi.i.i.i.M.MMM.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L27" Version="1.3435.0-i.i.i.i.i.i.iMi.i.i.i.i.M.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L28" Version="1.3435.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L29" Version="1.3435.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L30" Version="1.3435.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L31" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L32" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L33" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMM.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L34" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.iMM.MMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L35" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMM.iMM.iMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L36" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMM.MMM.iMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L37" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L38" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMMMMMi.M.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L39" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMMMMMi.M.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L40" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L41" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMM.iMMMiMMMMMMMMMMMMMM.iMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L42" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.MMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L43" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMi.MMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L44" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMiMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L45" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMiMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L46" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMiMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L47" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L48" Version="1.3435.0-i.i.i.i.i.i.iMMMMMM.iMMMMMM.i.i.i.MMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L49" Version="1.3435.0-i.i.i.i.i.i.iMMMM.i.i.MMMMi.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L50" Version="1.3435.0-i.i.i.i.i.i.iMMMi.i.i.iMi.M.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L51" Version="1.3435.0-i.i.i.i.i.i.iMMMi.i.i.i.MMMMi.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L52" Version="1.3435.0-i.i.i.i.i.i.iMMMM.i.i.i.iMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L53" Version="1.3435.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L54" Version="1.3435.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L55" Version="1.3435.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L56" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMi.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L57" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L58" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L59" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L60" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L61" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L62" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3435L63" Version="1.3435.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
