<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4770L00" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L01" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L02" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L03" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L04" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L05" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L06" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L07" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L08" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L09" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L10" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L11" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L12" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L13" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L14" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L15" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L16" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L17" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L18" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L19" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L20" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L21" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L22" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L23" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L24" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L25" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L26" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L27" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L28" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMi.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L29" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMiMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L30" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L31" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L32" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L33" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L34" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L35" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L36" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L37" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L38" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L39" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L40" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L41" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L42" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L43" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L44" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L45" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L46" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L47" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L48" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L49" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L50" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L51" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L52" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L53" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L54" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L55" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L56" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L57" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L58" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMM.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L59" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L60" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L61" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L62" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4770L63" Version="1.4770.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
