<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF2788L00" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L01" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L02" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L03" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L04" Version="1.2788.0-i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L05" Version="1.2788.0-i.i.i.i.i.i.i.iMM.iMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L06" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L07" Version="1.2788.0-i.i.i.i.i.i.i.i.iMMMiMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L08" Version="1.2788.0-i.i.i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L09" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L10" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L11" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L12" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L13" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L14" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L15" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L16" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L17" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L18" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L19" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L20" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L21" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L22" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L23" Version="1.2788.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L24" Version="1.2788.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L25" Version="1.2788.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L26" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L27" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L28" Version="1.2788.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L29" Version="1.2788.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L30" Version="1.2788.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L31" Version="1.2788.0-i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L32" Version="1.2788.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L33" Version="1.2788.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L34" Version="1.2788.0-i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L35" Version="1.2788.0-i.i.i.i.i.i.i.M.M.iMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L36" Version="1.2788.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L37" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L38" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMi.MMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L39" Version="1.2788.0-i.i.i.i.i.i.i.i.i.M.i.MMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L40" Version="1.2788.0-i.i.i.i.i.i.i.i.i.M.i.MMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L41" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L42" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L43" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L44" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L45" Version="1.2788.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L46" Version="1.2788.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L47" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L48" Version="1.2788.0-i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L49" Version="1.2788.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L50" Version="1.2788.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L51" Version="1.2788.0-i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L52" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L53" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L54" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L55" Version="1.2788.0-i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L56" Version="1.2788.0-i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L57" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L58" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.iMiMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L59" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L60" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.iMMMiMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L61" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.iMM.iMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L62" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.iMM.iMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF2788L63" Version="1.2788.0-i.i.i.i.i.i.i.i.i.i.i.iMM.iMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
