<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF6147L00" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMiMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L01" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L02" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L03" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L04" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L05" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L06" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L07" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L08" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L09" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L10" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L11" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMi.i.MMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L12" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.M.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L13" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.M.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L14" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L15" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L16" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L17" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L18" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L19" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L20" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L21" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMi.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L22" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.MMMMMMM.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L23" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.iMMMMMMMi.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L24" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.iMMMMMMMi.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L25" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMi.i.i.i.i.i.MMMMM.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L26" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.i.iMMMM.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L27" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.i.iMMMi.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L28" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMi.i.i.i.i.i.i.M.i.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L29" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L30" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L31" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L32" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L33" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L34" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L35" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L36" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L37" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L38" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L39" Version="1.6147.0-0" />
    <PackageReference Include="BAF6147L40" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMi.i.i.i.iMMMM.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L41" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L42" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L43" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L44" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L45" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L46" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L47" Version="1.6147.0-0" />
    <PackageReference Include="BAF6147L48" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L49" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L50" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L51" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.M.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L52" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L53" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L54" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L55" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L56" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L57" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L58" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L59" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L60" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L61" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L62" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF6147L63" Version="1.6147.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
