<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3392L00" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L01" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L02" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L03" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L04" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L05" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L06" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L07" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L08" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L09" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L10" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L11" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L12" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L13" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L14" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L15" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L16" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L17" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L18" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L19" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L20" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L21" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L22" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L23" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L24" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L25" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L26" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L27" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L28" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L29" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L30" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L31" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMiMMMMMi.i.MMMMMMMMMMMMMMMMMMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L32" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMi.M.MMi.i.iMMMMMMMMMMMMMMMMMi.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L33" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMi.i.iMi.i.MMMMMMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L34" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMiMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L35" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L36" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.iMiMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L37" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.M.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L38" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L39" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMiMM.i.i.MMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L40" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L41" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L42" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L43" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L44" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMM.i.i.i.MMi.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L45" Version="1.3392.0-i.i.i.i.i.i.iMM.iMMMMMi.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMi.i.i.MMM.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L46" Version="1.3392.0-i.i.i.i.i.i.i.i.i.MMi.iMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L47" Version="1.3392.0-i.i.i.i.i.i.i.i.i.i.i.MMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L48" Version="1.3392.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L49" Version="1.3392.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L50" Version="1.3392.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L51" Version="1.3392.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L52" Version="1.3392.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L53" Version="1.3392.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L54" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L55" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L56" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L57" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.iMM.MMMMMMMMMMMMMMi.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L58" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMMMM.MMM.iMMMMMMMMMMMMMi.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L59" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.MMMMMMMMMMMMMMMMM.MMM.iMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L60" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.MMMMMMMMMMMMMMMMM.MMM.iMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L61" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMMMMMM.iMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L62" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMMMMMM.iMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3392L63" Version="1.3392.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMMMM.MMMMiMMMMMMMMMMMMMMMM.iMi.MMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
