<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3463L00" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L01" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L02" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L03" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L04" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L05" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L06" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L07" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L08" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L09" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L10" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L11" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L12" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L13" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L14" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L15" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L16" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L17" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L18" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L19" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.MMM.i.MMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L20" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.iMi.i.iMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L21" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMi.i.i.MMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L22" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L23" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L24" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L25" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L26" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L27" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L28" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L29" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L30" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L31" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMi.MMMMi.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L32" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L33" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L34" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L35" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L36" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L37" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L38" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L39" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L40" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L41" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L42" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMi.iMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L43" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMi.iMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L44" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMM.iMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L45" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMM.iMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L46" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMM.iMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L47" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMM.iMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L48" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMM.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L49" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMM.iMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L50" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMM.iMMMMMMMMMMMMMM.i.M.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L51" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMM.iMMMMMMMMMMMMMM.iMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L52" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMi.iMMMMMMMMMMMMMM.iMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L53" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMM.iMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L54" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMM.iMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L55" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMM.iMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L56" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMM.iMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L57" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMi.iMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L58" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMi.MMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L59" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMi.iMM.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L60" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L61" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L62" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.M.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3463L63" Version="1.3463.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMM.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
