<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3950L00" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.iMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L01" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.iMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L02" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L03" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L04" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L05" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L06" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L07" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L08" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L09" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L10" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L11" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L12" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L13" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.M.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L14" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.M.i.i.i.M.MMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L15" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L16" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L17" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L18" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.iMM.i.i.i.MMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L19" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMM.i.i.i.MMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L20" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L21" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L22" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L23" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L24" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L25" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L26" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L27" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L28" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L29" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L30" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L31" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L32" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L33" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L34" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L35" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L36" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L37" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L38" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L39" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L40" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L41" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L42" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L43" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L44" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L45" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L46" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L47" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L48" Version="1.3950.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L49" Version="1.3950.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L50" Version="1.3950.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L51" Version="1.3950.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L52" Version="1.3950.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L53" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L54" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L55" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L56" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L57" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L58" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L59" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L60" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L61" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L62" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3950L63" Version="1.3950.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
