<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4506L00" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L01" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L02" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L03" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L04" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L05" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L06" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L07" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L08" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L09" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L10" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L11" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L12" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMiMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L13" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L14" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L15" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L16" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L17" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L18" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L19" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L20" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L21" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L22" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L23" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L24" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L25" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L26" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L27" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L28" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L29" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L30" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L31" Version="1.4506.0-0" />
    <PackageReference Include="BAF4506L32" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L33" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L34" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L35" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L36" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L37" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L38" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L39" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L40" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L41" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L42" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L43" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L44" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L45" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L46" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L47" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L48" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L49" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L50" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L51" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L52" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L53" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L54" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L55" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L56" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L57" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L58" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L59" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L60" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L61" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L62" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4506L63" Version="1.4506.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
