<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3410L00" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L01" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L02" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L03" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L04" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L05" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L06" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L07" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L08" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L09" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L10" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L11" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L12" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L13" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L14" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L15" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L16" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L17" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L18" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L19" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L20" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L21" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L22" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L23" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L24" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L25" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.MMMMi.MMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L26" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMi.i.i.MMMMi.iMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L27" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.i.iMMMM.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L28" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.i.MMMMMMi.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L29" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMM.iMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L30" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L31" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L32" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L33" Version="1.3410.0-i.i.i.i.i.i.i.i.i.iMMMMMi.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L34" Version="1.3410.0-i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L35" Version="1.3410.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L36" Version="1.3410.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L37" Version="1.3410.0-i.i.i.i.i.i.iMM.i.i.i.i.i.M.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L38" Version="1.3410.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L39" Version="1.3410.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L40" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L41" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L42" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMi.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L43" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMM.i.i.MMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L44" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMM.MMM.MMMMMMMMMMi.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L45" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.MMM.MMMMMMMMMMM.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L46" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.MMM.MMMMMMMMMMMMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L47" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMi.MMM.MMMMMMMMMMMMM.iMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L48" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L49" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L50" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L51" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMiMMMM.MMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L52" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.MMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L53" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMiMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L54" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMiMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L55" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMiMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L56" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMi.MMMMMMMMMMMMMMM.i.i.MMMMMMMMM.i.M.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L57" Version="1.3410.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMM.i.i.iMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L58" Version="1.3410.0-i.i.i.i.i.i.iMMMM.iMMMMMMMi.i.i.i.MMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L59" Version="1.3410.0-i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.MMMMMMMMMMMMMMM.iMMMMMMMMMMMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L60" Version="1.3410.0-i.i.i.i.i.i.i.i.i.i.iMMMMMi.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMi.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L61" Version="1.3410.0-i.i.i.i.i.i.i.i.i.i.i.MMiMM.i.i.MMMMMMMMMMMMMMMMMMi.MMMMM.MMMMM.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L62" Version="1.3410.0-i.i.i.i.i.i.iMi.i.i.i.i.MMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3410L63" Version="1.3410.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
