<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3451L00" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L01" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L02" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L03" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L04" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L05" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L06" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L07" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMM.MMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L08" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMM.MMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L09" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMM.iMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L10" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.iMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L11" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMi.i.i.MMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L12" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L13" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L14" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMM.M.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L15" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMM.iMM.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L16" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.i.iMMMMMMMMMi.i.i.i.i.iMMMMMMMM.i.M.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L17" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.MMMMMMMMMMi.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L18" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.i.MMMMMMMMMMi.i.M.i.i.MMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L19" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMM.iMM.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L20" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L21" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMi.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L22" Version="1.3451.0-i.i.i.i.i.i.i.iMMMM.i.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L23" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.MMi.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L24" Version="1.3451.0-i.i.i.i.i.i.i.i.i.MMMMM.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L25" Version="1.3451.0-i.i.i.i.i.i.i.i.i.iMMMM.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L26" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L27" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L28" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L29" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L30" Version="1.3451.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L31" Version="1.3451.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.MMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L32" Version="1.3451.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.MMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L33" Version="1.3451.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L34" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.iMMMMMMMMMMMiMi.MMMMMMMMMMMMi.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L35" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMiMM.MMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L36" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.iMMMMMMMMMMMMMiMM.MMMMMMMMMMMMMMi.MMi.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L37" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMM.i.MMMMMMMMMMMMMMMMiMM.MMMMMMMMMMMMMMiMMMM.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L38" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.i.MMMMMMMMMMMMMMMMiMM.iMMMMMMMMMMMM.iMMMM.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L39" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMi.i.MMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.iMMMM.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L40" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMM.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.iMMMM.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L41" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMiMMMM.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L42" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.iMMMMMMMMMMMM.iMMMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L43" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMiMMMM.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L44" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.iMMMMMMMMMMMM.iMMMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L45" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMiMi.i.iMMMMMMMMMMMi.i.iMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L46" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMiMi.i.MMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L47" Version="1.3451.0-i.i.i.i.i.i.iMM.iMMMi.M.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L48" Version="1.3451.0-i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.MMMMMMM.MMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L49" Version="1.3451.0-i.i.i.i.i.i.i.i.i.iMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L50" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.MMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMiMM.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L51" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.iMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMi.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L52" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L53" Version="1.3451.0-i.i.i.i.i.i.i.i.i.i.i.iMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L54" Version="1.3451.0-i.i.i.i.i.i.iMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L55" Version="1.3451.0-i.i.i.i.i.i.iMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L56" Version="1.3451.0-i.i.i.i.i.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L57" Version="1.3451.0-i.i.i.i.i.i.iMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L58" Version="1.3451.0-i.i.i.i.i.i.iMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L59" Version="1.3451.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L60" Version="1.3451.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L61" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L62" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3451L63" Version="1.3451.0-i.i.i.i.i.i.iMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
