<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3407L00" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L01" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L02" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L03" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L04" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L05" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L06" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L07" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L08" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L09" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L10" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L11" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L12" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L13" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L14" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L15" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L16" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L17" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L18" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L19" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L20" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L21" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L22" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L23" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L24" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L25" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMM.MMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L26" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMi.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L27" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.i.MMMMMMM.iMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L28" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMi.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L29" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMi.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L30" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMM.MMM.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L31" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.iMi.i.MMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L32" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMi.MMi.i.MMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L33" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L34" Version="1.3407.0-i.i.i.i.i.i.iMMMi.MMMMi.i.i.i.MMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L35" Version="1.3407.0-i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMM.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L36" Version="1.3407.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L37" Version="1.3407.0-i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L38" Version="1.3407.0-i.i.i.i.i.i.iMM.i.i.i.i.i.M.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L39" Version="1.3407.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L40" Version="1.3407.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L41" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L42" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L43" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L44" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L45" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L46" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMi.M.iMMMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L47" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.MMiMMMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L48" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMi.MMiMMMMMMMMMMMMMi.MMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L49" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMiMMMiMMMMMMMMMMMMMi.MMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L50" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMiMMMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L51" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMiMMMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L52" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMiMMMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L53" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMiMMMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L54" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMiMMMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L55" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMiMMMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L56" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMiMMMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L57" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMM.i.i.MMMMMMMMMMMMiMMMi.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L58" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.i.i.MMMMMMMMMMM.i.iMi.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L59" Version="1.3407.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMi.i.i.MMMMMMMMMMi.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L60" Version="1.3407.0-i.i.i.i.i.i.iMM.i.iMMMMMM.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMM.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L61" Version="1.3407.0-i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.MMMMMMMMMMMMiMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L62" Version="1.3407.0-i.i.i.i.i.i.i.i.i.i.i.iMMMi.i.iMMMMMMMMMMMM.MMMMMMMMMMMMMMi.MMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3407L63" Version="1.3407.0-i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
