<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3937L00" Version="1.3937.0-i.i.i.i.i.i.i.i.iMMMi.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L01" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L02" Version="1.3937.0-i.i.i.i.i.i.iMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L03" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L04" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L05" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L06" Version="1.3937.0-i.i.i.i.i.i.iMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L07" Version="1.3937.0-i.i.i.i.i.i.iMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L08" Version="1.3937.0-i.i.i.i.i.i.iMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L09" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L10" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L11" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L12" Version="1.3937.0-i.i.i.i.i.i.iMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L13" Version="1.3937.0-i.i.i.i.i.i.iMM.M.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L14" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.i.M.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L15" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L16" Version="1.3937.0-i.i.i.i.i.i.iMMMi.i.i.i.iMMMMMMMMMMMMMMMMMM.i.MMMMi.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L17" Version="1.3937.0-i.i.i.i.i.i.iMMMM.i.i.i.i.MMMMMMMMMMMMMMMMM.i.MMM.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L18" Version="1.3937.0-i.i.i.i.i.i.iMMMMMM.i.i.i.MMMMMMMMMMMMMMMMM.i.MMM.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L19" Version="1.3937.0-i.i.i.i.i.i.iMMMMMM.i.i.i.MMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L20" Version="1.3937.0-i.i.i.i.i.i.iMMMMMM.i.i.i.MMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L21" Version="1.3937.0-i.i.i.i.i.i.iMMMMMMMi.i.i.MMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L22" Version="1.3937.0-i.i.i.i.i.i.iMMMMMMMi.i.iMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L23" Version="1.3937.0-i.i.i.i.i.i.iMMMMMMMi.i.iMMMMMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L24" Version="1.3937.0-i.i.i.i.i.i.iMMMMMMMi.i.iMMMM.iMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L25" Version="1.3937.0-i.i.i.i.i.i.iMMMMMMMi.i.iMMMi.iMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L26" Version="1.3937.0-i.i.i.i.i.i.iMMMMMM.i.i.iMMMi.i.MMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L27" Version="1.3937.0-i.i.i.i.i.i.iMMMMMi.i.i.iMMMM.MMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L28" Version="1.3937.0-i.i.i.i.i.i.iMMMM.i.i.i.i.MMM.MMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L29" Version="1.3937.0-i.i.i.i.i.i.iMMMM.i.i.i.i.MMMMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L30" Version="1.3937.0-i.i.i.i.i.i.iMMMi.i.i.i.i.MMMMMMMMMMMMMMMMM.iMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L31" Version="1.3937.0-i.i.i.i.i.i.iMMMi.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L32" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L33" Version="1.3937.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.MMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L34" Version="1.3937.0-i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.MMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L35" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L36" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L37" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMM.iMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L38" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.iMMMMMM.iMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L39" Version="1.3937.0-0" />
    <PackageReference Include="BAF3937L40" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.MMMMM.iMiMMMi.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L41" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.iMMMM.i.i.M.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L42" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L43" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L44" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L45" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L46" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L47" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L48" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L49" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L50" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L51" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L52" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L53" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L54" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L55" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L56" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L57" Version="1.3937.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L58" Version="1.3937.0-i.i.i.i.i.i.iMMMM.i.i.i.i.MMMMi.i.i.i.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L59" Version="1.3937.0-i.i.i.i.i.i.iMMMMMi.i.i.MMMMMMi.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L60" Version="1.3937.0-i.i.i.i.i.i.iMMMMMi.i.i.MMMMMMi.i.i.i.i.i.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L61" Version="1.3937.0-i.i.i.i.i.i.iMMMMMi.i.i.MMMMMMi.i.i.i.i.M.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L62" Version="1.3937.0-i.i.i.i.i.i.iMMMM.i.i.iMMMMMMMM.i.i.i.i.M.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3937L63" Version="1.3937.0-i.i.i.i.i.i.iMMMM.i.i.iMMMMMMMMMM.i.i.iMM.i.MMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
