<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4133L00" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L01" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L02" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L03" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L04" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L05" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L06" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L07" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L08" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L09" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L10" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L11" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L12" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L13" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L14" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L15" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L16" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L17" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L18" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L19" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L20" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L21" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L22" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L23" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L24" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L25" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L26" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L27" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L28" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L29" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L30" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L31" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L32" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L33" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L34" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L35" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L36" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L37" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L38" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L39" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L40" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L41" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L42" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L43" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.M.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L44" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.M.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L45" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L46" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L47" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L48" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L49" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L50" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L51" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L52" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L53" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L54" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L55" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L56" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L57" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L58" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L59" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L60" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L61" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L62" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMi.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4133L63" Version="1.4133.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMi.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
