<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF5010L00" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.M.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L01" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L02" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L03" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L04" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L05" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L06" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L07" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L08" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L09" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L10" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L11" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L12" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L13" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L14" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.MMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L15" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L16" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L17" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L18" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L19" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMi.i.MMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L20" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMi.i.MMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L21" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.MMMMMMM.i.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L22" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.i.MMMMMMi.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L23" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMM.iMMMMMMMi.i.i.i.i.i.i.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L24" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L25" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L26" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMiMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L27" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMiMM.i.i.i.MMMMMMMMMMMMM.MMMMi.i.i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L28" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMiMM.i.i.i.MMMMMMMMMMMMM.iMM.i.i.i.i.i.i.i.i.iMM.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L29" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L30" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L31" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMiMiMi.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L32" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMiMiMi.i.i.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L33" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMiMiMM.i.i.i.MMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L34" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMM.i.i.i.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L35" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMi.i.i.i.MMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L36" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMi.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L37" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.MMiMMMi.i.i.i.iMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L38" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.MMiMMMM.i.i.i.i.MMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L39" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.MMiMMMMMi.i.i.i.iMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L40" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.M.iMMMMMi.i.i.i.iMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L41" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMM.i.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L42" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMM.i.i.i.i.M.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L43" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L44" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L45" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L46" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L47" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L48" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L49" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.MMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L50" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMiMM.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L51" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMiMM.MMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L52" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMiMi.MMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L53" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L54" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L55" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L56" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L57" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L58" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L59" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L60" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMMMi.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L61" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMM.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L62" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMM.iMiMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF5010L63" Version="1.5010.0-i.i.i.i.i.i.iMMMMMMMMMM.MMiMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
