<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3533L00" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L01" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L02" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L03" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L04" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMMMiMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L05" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMM.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L06" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L07" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L08" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L09" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L10" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L11" Version="1.3533.0-i.i.i.i.i.i.iMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L12" Version="1.3533.0-i.i.i.i.i.i.iMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L13" Version="1.3533.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L14" Version="1.3533.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L15" Version="1.3533.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L16" Version="1.3533.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L17" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L18" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L19" Version="1.3533.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L20" Version="1.3533.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L21" Version="1.3533.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L22" Version="1.3533.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L23" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L24" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L25" Version="1.3533.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L26" Version="1.3533.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L27" Version="1.3533.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L28" Version="1.3533.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L29" Version="1.3533.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L30" Version="1.3533.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L31" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMiMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L32" Version="1.3533.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L33" Version="1.3533.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L34" Version="1.3533.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L35" Version="1.3533.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L36" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L37" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L38" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L39" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L40" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L41" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L42" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L43" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.iMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L44" Version="1.3533.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L45" Version="1.3533.0-i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L46" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L47" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L48" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L49" Version="1.3533.0-i.i.i.i.i.i.i.i.MMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L50" Version="1.3533.0-i.i.i.i.i.i.i.MMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L51" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L52" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L53" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L54" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L55" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L56" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L57" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L58" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L59" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L60" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L61" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L62" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3533L63" Version="1.3533.0-i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
