<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3424L00" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L01" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L02" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L03" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L04" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L05" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L06" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L07" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L08" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L09" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L10" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L11" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L12" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L13" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L14" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMM.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L15" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L16" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L17" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L18" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L19" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.iMiMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L20" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMM.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L21" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L22" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.i.MMMMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L23" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMi.i.i.M.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L24" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L25" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L26" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L27" Version="1.3424.0-i.i.i.i.i.i.iMMMMMiMMMMMMMi.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L28" Version="1.3424.0-i.i.i.i.i.i.iMi.i.i.MMMMi.i.i.i.MMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMi.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L29" Version="1.3424.0-i.i.i.i.i.i.i.i.i.i.i.i.i.M.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L30" Version="1.3424.0-i.i.i.i.i.i.iMi.i.i.i.i.MMMMi.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L31" Version="1.3424.0-i.i.i.i.i.i.iMM.i.i.i.i.i.M.i.i.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L32" Version="1.3424.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L33" Version="1.3424.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.iMMMMMMMMMMMM.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L34" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L35" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMi.i.i.iMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L36" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L37" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L38" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L39" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.MMMMMMMMMMM.iMiMMMMMMMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L40" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMM.MMiMMMMMMMMMMMMMM.iMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L41" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMM.MMiMMMMMMMMMMMMMi.MMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L42" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMM.MMiMMMMMMMMMMMMMi.MMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L43" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMM.MMiMMMMMMMMMMMM.iMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L44" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMM.MMiMMMMMMMMMMMM.iMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L45" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.i.iMMMMMMMMMM.iMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L46" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMi.i.i.iMMMMMMMMMM.MMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L47" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMM.i.i.iMMMMMMMMMM.MMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L48" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMMMM.i.i.MMMMMMMMMMi.MMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L49" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.iMMMMMMMMMi.MMMMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L50" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMMMi.M.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L51" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMi.i.i.MMMMMMMMi.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L52" Version="1.3424.0-i.i.i.i.i.i.iMMMMMi.iMMMMMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L53" Version="1.3424.0-i.i.i.i.i.i.iMMMi.i.i.MMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMiMMMMMMMi.i.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L54" Version="1.3424.0-i.i.i.i.i.i.iMM.i.i.i.i.iMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L55" Version="1.3424.0-i.i.i.i.i.i.iMMMi.i.i.i.MMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L56" Version="1.3424.0-i.i.i.i.i.i.iMMMM.i.i.i.iMMMi.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L57" Version="1.3424.0-i.i.i.i.i.i.iMMMM.i.i.i.i.M.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L58" Version="1.3424.0-i.i.i.i.i.i.iMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMi.i.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L59" Version="1.3424.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L60" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMM.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L61" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L62" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3424L63" Version="1.3424.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
