<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF3443L00" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L01" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L02" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L03" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L04" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L05" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L06" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L07" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMiMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L08" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L09" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMM.MMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L10" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMi.i.iMM.i.iMMMMMMMMMMMMMMMMMMMi.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L11" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.MMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L12" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L13" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L14" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.MMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L15" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L16" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.MMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L17" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMi.i.iMiMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L18" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMM.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L19" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMi.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L20" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L21" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L22" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMM.i.i.iMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L23" Version="1.3443.0-i.i.i.i.i.i.iMM.i.iMMMM.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMMMMMMMM.i.i.iMi.i.i.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L24" Version="1.3443.0-i.i.i.i.i.i.i.i.i.i.M.i.MMi.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMMMMMM.i.i.MMMMiMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L25" Version="1.3443.0-i.i.i.i.i.i.i.i.i.i.i.iMMMi.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L26" Version="1.3443.0-i.i.i.i.i.i.i.i.i.i.i.iMi.i.i.MMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L27" Version="1.3443.0-i.i.i.i.i.i.iMM.i.i.i.i.i.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L28" Version="1.3443.0-i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L29" Version="1.3443.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L30" Version="1.3443.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.i.i.MMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L31" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.i.i.MMMMMMMMM.i.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L32" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.MMMMMMMMMMi.i.i.iMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L33" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMiMM.iMMMMMMMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L34" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.iMMMMMMMMMMMMMiMMMiMMMMMMMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L35" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMiMMMiMMMMMMMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L36" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMiMMMiMMMMMMMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L37" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.MMMMMMMMMMMMMMMMiMMMiMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L38" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMMMiMMMi.MMMMMMMMMMMMMMM.iMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L39" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.MMi.MMMMMMMMMMMMMMi.iMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L40" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.MMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMi.MMiMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L41" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.MMMMMMMMMMMMM.iMM.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L42" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMMMM.i.i.iMMMMMMMMMMMMMM.iMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L43" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.MMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L44" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.MMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.MMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L45" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMM.MMMMi.iMMMMMMMMMMMMMi.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L46" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMiMi.MMMMMMMMMMMMMMMMi.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L47" Version="1.3443.0-i.i.i.i.i.i.iMMMM.i.MMMMMMi.i.i.MMMMMMMMMMiMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L48" Version="1.3443.0-i.i.i.i.i.i.iMMMi.i.iMMMi.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L49" Version="1.3443.0-i.i.i.i.i.i.iMi.i.i.i.i.MMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L50" Version="1.3443.0-i.i.i.i.i.i.iMM.i.i.i.iMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L51" Version="1.3443.0-i.i.i.i.i.i.iMMMi.i.i.i.MMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L52" Version="1.3443.0-i.i.i.i.i.i.iMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L53" Version="1.3443.0-i.i.i.i.i.i.iMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.MMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L54" Version="1.3443.0-i.i.i.i.i.i.iMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMi.i.i.iMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L55" Version="1.3443.0-i.i.i.i.i.i.iMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMi.i.M.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L56" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMi.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L57" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L58" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L59" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L60" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L61" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L62" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF3443L63" Version="1.3443.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
