<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4966L00" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L01" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L02" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L03" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L04" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L05" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L06" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L07" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L08" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L09" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L10" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L11" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L12" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L13" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L14" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMiMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L15" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L16" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMi.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L17" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L18" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMM.i.i.i.iMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L19" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMi.i.i.iMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L20" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMM.i.i.iMMMi.i.iMMMi.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L21" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.iMMMi.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L22" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L23" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMMMMMi.i.i.i.i.i.iMMMi.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L24" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.iMM.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L25" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L26" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.MMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L27" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L28" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.MMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L29" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMi.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L30" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.iMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L31" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.M.i.i.MMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L32" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMi.i.i.iMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L33" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMi.i.i.iMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L34" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMM.i.i.i.MMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L35" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMi.i.i.iMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L36" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.M.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L37" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMiMMMMMi.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L38" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L39" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L40" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L41" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L42" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L43" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMMMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L44" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L45" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L46" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L47" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.MMMMMMMMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L48" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L49" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L50" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.MMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L51" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L52" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L53" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L54" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.iMMMMMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L55" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L56" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L57" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L58" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L59" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L60" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMi.MMMMMMMMMMM.i.i.i.i.iMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L61" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.iMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L62" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.iMi.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4966L63" Version="1.4966.0-i.i.i.i.i.i.iMMMMMMMMMMMMMM.iMMMMMMMMMMMM.i.i.i.i.iMM.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
