<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BAF4876L00" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L01" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L02" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L03" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMiMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L04" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L05" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L06" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L07" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L08" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L09" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L10" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMi.i.iMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L11" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L12" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.MMMMMMMMMMMMMMMMMMMMMMMMi.i.i.i.MMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L13" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.MMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L14" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.MMMMMMMMMMMMMMMMi.MMi.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L15" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMi.M.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L16" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L17" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L18" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.MMMMi.i.i.i.i.i.M.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L19" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.iMMMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L20" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L21" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L22" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L23" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.iMi.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L24" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L25" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L26" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L27" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMM.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L28" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L29" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMM.i.i.i.i.i.i.i.i.M.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L30" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMi.i.i.i.i.i.i.iMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L31" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.MMMMi.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L32" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMi.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L33" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L34" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMM.i.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L35" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMM.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L36" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMi.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L37" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMMMi.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L38" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.iMMMMMM.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L39" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.iMMMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L40" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.iMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L41" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L42" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L43" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L44" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L45" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.i.iMM.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L46" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.iMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L47" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L48" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L49" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L50" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L51" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L52" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L53" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMM.i.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L54" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L55" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L56" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMMMi.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L57" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.MMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L58" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMi.MMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L59" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L60" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMiMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L61" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.i.i.MMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L62" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMM.iMMMMMM.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
    <PackageReference Include="BAF4876L63" Version="1.4876.0-i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMiMiMMMMMi.i.i.i.i.i.i.i.i.iMMMMMMMMMMMMMMMMMMMM.i.i.i.i.i.ii" />
  </ItemGroup>
</Project>
